[version]
current = "0.4.1"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (
    -
    (?P<channel>alpha|beta|r)
    (?P<release>\d+)
  )?
'''

[git]
tag_template = "v{new_version}"
message_template = "Bump to {new_version}"

[[file]]
src = "setup.py"

[[hook]]
name = "publish"
cmd = "./publish.sh"
